name: Build OrangeFox Recovery

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'  # Agrega esta línea para especificar la distribución

      - name: Build OrangeFox
        run: |
          chmod +x build.sh
          ./build.sh
