name: Build OrangeFox Recovery

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build OrangeFox
        run: |
          cd Recovery-Builder-NoKernel  # Cambia al directorio donde está build.sh
          chmod +x build.sh
          ./build.sh
