name: Build OrangeFox Recovery

on:
  push:
    branches:
      - master  # Asegúrate de que esto sea la rama correcta donde estás trabajando

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # Cambia a '17' si estás utilizando JDK 17
          distribution: 'temurin'  # Añade esto para especificar la distribución de Java

      - name: Build OrangeFox
        run: |
          chmod +x build.sh  # Asegúrate de que la ruta sea correcta
          ./build.sh         # Asegúrate de que la ruta sea correcta
